# Generated by Django 5.0.7 on 2025-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
