# Generated by Django 5.0.7 on 2025-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_name_baseuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
