# Generated by Django 5.0.7 on 2025-03-04 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_courses', to='educa.faculty')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_students', to='educa.faculty')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('deactiveted_at', models.DateField(blank=True, null=True)),
                ('faculty_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='educa.facultycourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='educa.student')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
            },
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='faculty_course_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='facultycourse',
            unique_together={('name', 'slug', 'start_date', 'end_date')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('email', 'faculty'), ('identifier', 'faculty')},
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='roster_start_before_end'),
        ),
    ]
