# Generated by Django 5.0.7 on 2025-03-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0003_alter_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('identifier', 'faculty'), ('identifier', 'user')},
        ),
    ]
