# Generated by Django 5.0.7 on 2025-03-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0004_alter_student_user_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
