# Generated by Django 5.0.7 on 2025-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0005_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facultycourse',
            unique_together={('name', 'faculty', 'start_date', 'end_date')},
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('student', 'faculty_course', 'start_date', 'end_date'), name='unigue_roster'),
        ),
    ]
