# Generated by Django 5.0.7 on 2025-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0006_alter_facultycourse_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roster',
            name='unigue_roster',
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('student', 'faculty_course'), name='unigue_roster'),
        ),
    ]
