# Generated by Django 5.0.7 on 2025-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0007_remove_roster_unigue_roster_roster_unigue_roster'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roster',
            name='unigue_roster',
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('student', 'faculty_course', 'start_date', 'end_date'), name='unigue_roster'),
        ),
    ]
