# Generated by Django 5.0.7 on 2025-03-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0011_exercise_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice',
            new_name='choice_answer',
        ),
    ]
