# Generated by Django 5.0.7 on 2025-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0012_rename_choice_question_choice_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(related_name='task_exercises', to='educa.exercise')),
            ],
            options={
                'verbose_name': 'Контрольная работа',
                'verbose_name_plural': 'Контрольные работы',
            },
        ),
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='test_questions', to='educa.question')),
            ],
            options={
                'verbose_name': 'Контрольный тест',
                'verbose_name_plural': 'Контрольные тесты',
            },
        ),
    ]
