# Generated by Django 5.0.7 on 2025-03-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0013_controltask_controltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltask',
            name='avarage_rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='controltest',
            name='avarage_rank',
            field=models.FloatField(default=0.0),
        ),
    ]
