# Generated by Django 5.0.7 on 2025-03-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0014_controltask_avarage_rank_controltest_avarage_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controltask',
            old_name='avarage_rank',
            new_name='average_rank',
        ),
        migrations.RenameField(
            model_name='controltest',
            old_name='avarage_rank',
            new_name='average_rank',
        ),
    ]
