# Generated by Django 5.0.7 on 2025-03-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0015_rename_avarage_rank_controltask_average_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltask',
            name='faculty_course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='control_tasks', to='educa.facultycourse'),
        ),
    ]
