# Generated by Django 5.0.7 on 2025-03-18 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0016_controltask_faculty_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltest',
            name='faculty_course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='control_tests', to='educa.facultycourse'),
        ),
        migrations.AddField(
            model_name='roster',
            name='control_task',
            field=models.JSONField(default={}),
        ),
    ]
