# Generated by Django 5.0.7 on 2025-03-18 10:33

import django.db.models.deletion
import education.education_apps.educa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0017_controltest_faculty_course_roster_control_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='control_task',
        ),
        migrations.CreateModel(
            name='ControlTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=education.education_apps.educa.models.default_control)),
                ('score', models.FloatField(default=0.0)),
                ('control_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='educa.controltask')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_task_results', to='educa.roster')),
            ],
            options={
                'verbose_name': 'Результат контрольной работы',
                'verbose_name_plural': 'Результаты контрольных работ',
            },
        ),
        migrations.CreateModel(
            name='ControlTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=education.education_apps.educa.models.default_control)),
                ('score', models.FloatField(default=0.0)),
                ('check_in', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='educa.controltest')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_test_results', to='educa.roster')),
            ],
            options={
                'verbose_name': 'Результат контрольного теста',
                'verbose_name_plural': 'Результаты контрольных тестов',
            },
        ),
        migrations.AddConstraint(
            model_name='controltaskresult',
            constraint=models.UniqueConstraint(fields=('roster', 'control_task'), name='unigue_control_task_result'),
        ),
        migrations.AddConstraint(
            model_name='controltestresult',
            constraint=models.UniqueConstraint(fields=('roster', 'control_test'), name='unigue_control_test_result'),
        ),
    ]
