# Generated by Django 5.0.7 on 2025-03-19 13:45

import education.education_apps.educa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0018_remove_roster_control_task_controltaskresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltestresult',
            name='done_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controltestresult',
            name='answers',
            field=models.JSONField(blank=True, default=education.education_apps.educa.models.default_control, null=True),
        ),
    ]
