# Generated by Django 5.0.7 on 2025-03-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0019_controltestresult_done_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controltestresult',
            name='done_at',
        ),
    ]
