# Generated by Django 5.0.7 on 2025-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0020_remove_controltestresult_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltaskresult',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
