# Generated by Django 5.0.7 on 2025-03-20 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0021_controltaskresult_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltaskresult',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
